# Generated by Django 4.2.4 on 2023-08-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=14)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encargos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GastosFixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HorasProdutivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('jornada_diaria', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('permissao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_proposta', models.DateField()),
                ('aprovada', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='GastosVariaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.colaboradores')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('numero_empresa', models.DecimalField(decimal_places=0, max_digits=3)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('ativa', models.BooleanField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.endereco'),
        ),
    ]
