# Generated by Django 4.2.4 on 2023-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_colaboradores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_empresa',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
