# Generated by Django 4.2.4 on 2023-08-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_empresa_numero_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='endereco',
        ),
    ]
