# Generated by Django 4.2.4 on 2023-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_colaboradores_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=30),
        ),
    ]
