# Generated by Django 4.2.4 on 2023-08-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_endereco_logradouro_alter_endereco_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('dias_uteis', models.PositiveIntegerField()),
                ('horas_produtivas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.colaboradores')),
            ],
        ),
    ]
