# Generated by Django 4.2.4 on 2023-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_calendariomensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariomensal',
            name='jornada_diaria',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
